version: '3'
services:
  backend:
    build: .
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - bets_db

  bets_db:
    image: postgres:latest
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - bets_db_data:/var/lib/postgresql/data

volumes:
  bets_db_data:

