from decouple import config

class Settings:
    POSTGRESQL_HOST = config('POSTGRESQL_HOST')
    POSTGRESQL_PORT = config('POSTGRESQL_PORT')
    POSTGRESQL_DB = config('POSTGRESQL_DB')
    POSTGRESQL_USER = config('POSTGRESQL_USER')
    POSTGRESQL_PASSWORD = config('POSTGRESQL_PASSWORD')
    POSTGRESQL_URI = f'postgresql+asyncpg://{POSTGRESQL_USER}:{POSTGRESQL_PASSWORD}@{POSTGRESQL_HOST}:{POSTGRESQL_PORT}/{POSTGRESQL_DB}'
