from decouple import config


class Settings:
    POSTGRESQL_HOST = config("POSTGRES_HOST")
    POSTGRESQL_PORT = config("POSTGRES_PORT")
    POSTGRESQL_DB = config("POSTGRES_DB")
    POSTGRESQL_USER = config("POSTGRES_USER")
    POSTGRESQL_PASSWORD = config("POSTGRES_PASSWORD")
    POSTGRESQL_URI = f"postgresql+asyncpg://{POSTGRESQL_USER}:{POSTGRESQL_PASSWORD}@{POSTGRESQL_HOST}:{POSTGRESQL_PORT}/{POSTGRESQL_DB}"
